### ISSUE TITLE
Decide what imports we want to show in the book, and eliminate the others

### ISSUE THREAD

**Issue by BruceEckel** [EffectOrientedProgramming/book#455]
Might be a more useful strategy to use a whitelist; it seems like we might currently be using a blacklist approach

**Comment by swoogles** [comment]
Which ones are you thinking we should show/hide VS what we are currently doing?

**Comment by BruceEckel** [comment]
I'm wondering about zio.test.* as it seems like it might fit in the "default" category with its number of repetitions
If someone is going to experiment with the code they will go to the examples repo and everything will be there, so it seems like we only need to call out something like the zio.test stuff when it is first used.

I also found this one had slipped through:
`import zio.{Console, *}`

I would imagine this shouldn't be in the book:
`import CircuitBreaker.CircuitBreakerOpen`

But that's it. I think removing `zio.test` stuff would be the biggest noise reduction. I can add a paragraph if necessary to explain that whenever they see `def spec` that means `zio.test` stuff is automatically imported, and that they should start experimenting with code via the examples repo.

**Comment by swoogles** [comment]
The `zio.test.*` import is made surprisingly difficult by the fact that there is the `zio.test` package, and the `zio.test.test` type.

I attempted to take the same approach that we do with `import zio.*` and `import zio.defer.*`, but it doesn't work 😞 

We can do a heavy-handed "Replace all occurrences of `import zio.test.*` from the final manuscript, but we'd have to make sure that it doesn't blast any place where we're trying to explain "We don't need to explicitly do `import zio.test.*` because blah blah tooling".

**Comment by jamesward** [comment]
With the sbt-based imports we have too many places where imports get set and modified. We've also been doing most imports in mdoc codefences because IntelliJ is happier. So in an attempt to simplify things I've switched to controlling imports universally:
https://github.com/EffectOrientedProgramming/book/commit/14a1a50435193c8928be57219ec0f86d87b842c8

This means that in mdoc codefences we import what we need, then we later remove them from the manuscript and examples. But there are imports we inject into the examples:
```
import zio.*
import zio.direct.*
import zio.Console.*
import zio.test.* // only in `src/test/scala`
```

I think this is a more manageable approach because it reduces some complexity. However, it does mean that more verbose `Chapters` mdoc code which I think we are ok with since we've already gone that path for IntelliJ.

For the question about what imports we show, I think in manuscript, we should not show any `import zio` with one exception, in **Testing** we have to do an `import zio.test.test` to get the right `test()` but that one should be preserved in manuscript & examples.
